### ISSUE TITLE
License

### ISSUE THREAD

**Issue by johan-andersson01** [zaccharieramzi/tf-slice-assign#6]
Hi there,

Thanks for saving some hours of my life :)

What's the license for this? Saw that you had specified MIT in the pip repository, but just wanted to make sure!

**Comment by zaccharieramzi** [comment]
Hi !

Glad it helper, if you have any feedback in addition to the license it will be greatly appreciated.

It's the first time I do an open source project form scratch so I didn't think the license was the first things to put, but it seems important actually.
I indeed chose the MIT license for this project.
